### ISSUE TITLE
fix: example in readme.md is not correct

### ISSUE THREAD

**Issue by panapol-p** [panapol-p/go-slice-struct-diff#7]
we update NewListener to NewDiff (ref. #5)
![image](https://user-images.githubusercontent.com/34530268/196046775-602064c3-d70e-428e-bf09-91d241443645.png)

**Comment by najeebkp** [comment]
hi @panapol-p please assign this to me

**Comment by panapol-p** [comment]
Hi @najeebkp , it will be great!
